### ISSUE TITLE
Units for the x-axis

### ISSUE THREAD

**Issue by idontgetoutmuch** [lehins/haskell-benchmarks#1]
Great post: https://alexey.kuleshevi.ch/blog/2019/12/21/random-benchmarks/ :)

One minor point: I am having to guess the units on the x-axis. Are they seconds, milliseconds, microseconds or something else?

**Comment by lehins** [comment]
The actual scale does not matter, because I never specified the size of the array that is being generated. I could just as well increase the size of the array by a 1000 and it will go from `ms` to `s`.

That being said, benchmarks are interactive, so if you hover a particular benchmark you'll get the actual value ;)

**Comment by idontgetoutmuch** [comment]
I suppose it comes of having worked in data for a long time and you *always* label your axes.
